### ISSUE TITLE
TF DQN Pong example is broken

### ISSUE THREAD

**Issue by zplizzi** [rlworkgroup/garage#1102]
Running

`python examples/tf/dqn_pong.py`

gives the error
```
Traceback (most recent call last):
  File "/home/ubuntu/.pyenv/versions/3.6.8/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ubuntu/.pyenv/versions/3.6.8/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/.pyenv/versions/3.6.8/lib/python3.6/site-packages/garage/experiment/experiment_wrapper.py", line 251, in <module>
    run_experiment(sys.argv)
  File "/home/ubuntu/.pyenv/versions/3.6.8/lib/python3.6/site-packages/garage/experiment/experiment_wrapper.py", line 166, in run_experiment
    args.resume_from_epoch)
  File "examples/tf/dqn_pong.py", line 87, in run_task
    buffer_batch_size=32)
TypeError: __init__() got an unexpected keyword argument 'steps_per_epoch'
```

This is with the most recent version of garage available via pip, and a copy of this repo from moments ago.

**Comment by zplizzi** [comment]
Whoops, it works if I install garage from source. Must have been a change in the API since the last pip release.

**Comment by ryanjulian** [comment]
@zplizzi thanks for trying out the software! you can always see the exact code in each release by consulting the release tag or branch.

Assuming you are installing from the latest pip, those are:
Tag: https://github.com/rlworkgroup/garage/tree/v2019.10.1
Branch: https://github.com/rlworkgroup/garage/tree/release-2019.10

If you want a more cutting-edge copy, you can install the latest pre-release: `pip install garage==2020.02.0rc1`  (which also has a corresponding tag)

Let us know if you have any other questions!

**Comment by zplizzi** [comment]
Thanks!
