### ISSUE TITLE
Using a trained policy inside custom environment

### ISSUE THREAD

**Issue by mdalvi** [rlworkgroup/garage#1312]
I have a custom environment like 1 vs 1 poker game where I am trying to battle policies. 

Is it possible to execute `policy.get_action()` within a `TfEnv`?

My naive initial approach was as follows,

```
# custom env
class Poker(gym.Env):
    def __init__(self, args, config):
        super(Poker, self).__init__()
        self.args = args
        self.config = config

        # i am hoping to use default session provided by garage!
        experiment = joblib.load(Path('data/local/experiment/experiment_1/params.pkl'))
        policy = experiment['algo'].policy

        self.tournament = HeadsUp(args, config, policy)


# somewhere inside environment
class MachinePlayer(Player):

    def __init__(self, args, config, policy):
        super(MachinePlayer, self).__init__()
        self.args = args
        self.config = config
        self.policy = policy

    def act(self, state):
        return self.policy.get_action(state)[0]
```
And here is the main.py that handles this environment
```
def run_task(self, snapshot_config, variant, *_):
    with LocalTFRunner(snapshot_config=snapshot_config) as runner:
        config = Config()
        config.initialize(Path(f'config/templates/{self.args.config}'))

        env = TfEnv(env=Poker(self.args, config))

        policy = CategoricalMLPPolicy(name='policy', env_spec=env.spec, hidden_sizes=(32, 32))
        baseline = LinearFeatureBaseline(env_spec=env.spec)
        algorithm = TRPO(env_spec=env.spec, policy=policy, baseline=baseline, max_path_length=100, discount=0.99,
                         max_kl_step=0.01)

        runner.setup(algorithm, env)
        runner.train(n_epochs=100, batch_size=256)
            
run_experiment(self.run_task, snapshot_mode="last", seed=1, force_cpu=True)
```

I get the below error,
```
Traceback (most recent call last):
  File "/home/mdalvi/miniconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/mdalvi/miniconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/mdalvi/miniconda3/lib/python3.7/site-packages/garage/experiment/experiment_wrapper.py", line 251, in <module>
    run_experiment(sys.argv)
  File "/home/mdalvi/miniconda3/lib/python3.7/site-packages/garage/experiment/experiment_wrapper.py", line 166, in run_experiment
    args.resume_from_epoch)
  File "/home/mdalvi/Documents/poker-assistant/engine/simulator.py", line 61, in run_task
    policy = CategoricalMLPPolicy(name='policy', env_spec=env.spec, hidden_sizes=(32, 32))
  File "/home/mdalvi/miniconda3/lib/python3.7/site-packages/garage/tf/policies/categorical_mlp_policy.py", line 75, in __init__
    self._initialize()
  File "/home/mdalvi/miniconda3/lib/python3.7/site-packages/garage/tf/policies/categorical_mlp_policy.py", line 83, in _initialize
    self.model.build(state_input)
  File "/home/mdalvi/miniconda3/lib/python3.7/site-packages/garage/tf/models/base.py", line 198, in build
    network._outputs = self._build(*inputs, name)
  File "/home/mdalvi/miniconda3/lib/python3.7/site-packages/garage/tf/models/mlp_model.py", line 75, in _build
    layer_normalization=self._layer_normalization)
  File "/home/mdalvi/miniconda3/lib/python3.7/site-packages/garage/tf/models/mlp.py", line 83, in mlp
    name='hidden_{}'.format(idx))
  File "/home/mdalvi/miniconda3/lib/python3.7/site-packages/tensorflow_core/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/home/mdalvi/miniconda3/lib/python3.7/site-packages/tensorflow_core/python/layers/core.py", line 187, in dense
    return layer.apply(inputs)
  File "/home/mdalvi/miniconda3/lib/python3.7/site-packages/tensorflow_core/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/home/mdalvi/miniconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 1700, in apply
    return self.__call__(inputs, *args, **kwargs)
  File "/home/mdalvi/miniconda3/lib/python3.7/site-packages/tensorflow_core/python/layers/base.py", line 548, in __call__
    outputs = super(Layer, self).__call__(inputs, *args, **kwargs)
  File "/home/mdalvi/miniconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 824, in __call__
    self._maybe_build(inputs)
  File "/home/mdalvi/miniconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 2146, in _maybe_build
    self.build(input_shapes)
  File "/home/mdalvi/miniconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/layers/core.py", line 1021, in build
    trainable=True)
  File "/home/mdalvi/miniconda3/lib/python3.7/site-packages/tensorflow_core/python/layers/base.py", line 461, in add_weight
    **kwargs)
  File "/home/mdalvi/miniconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 529, in add_weight
    aggregation=aggregation)
  File "/home/mdalvi/miniconda3/lib/python3.7/site-packages/tensorflow_core/python/training/tracking/base.py", line 712, in _add_variable_with_custom_getter
    **kwargs_for_getter)
  File "/home/mdalvi/miniconda3/lib/python3.7/site-packages/tensorflow_core/python/ops/variable_scope.py", line 1500, in get_variable
    aggregation=aggregation)
  File "/home/mdalvi/miniconda3/lib/python3.7/site-packages/tensorflow_core/python/ops/variable_scope.py", line 1243, in get_variable
    aggregation=aggregation)
  File "/home/mdalvi/miniconda3/lib/python3.7/site-packages/tensorflow_core/python/ops/variable_scope.py", line 567, in get_variable
    aggregation=aggregation)
  File "/home/mdalvi/miniconda3/lib/python3.7/site-packages/tensorflow_core/python/ops/variable_scope.py", line 519, in _true_getter
    aggregation=aggregation)
  File "/home/mdalvi/miniconda3/lib/python3.7/site-packages/tensorflow_core/python/ops/variable_scope.py", line 868, in _get_single_variable
    (err_msg, "".join(traceback.format_list(tb))))
ValueError: Variable policy/MLPModel/mlp/hidden_0/kernel already exists, disallowed. Did you mean to set reuse=True or reuse=tf.AUTO_REUSE in VarScope? Originally defined at:

  File "/home/mdalvi/miniconda3/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()
  File "/home/mdalvi/miniconda3/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "/home/mdalvi/miniconda3/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "/home/mdalvi/miniconda3/lib/python3.7/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/mdalvi/miniconda3/lib/python3.7/site-packages/tensorflow_core/python/framework/op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
```

I guess it's not able to handle two policies in one session, any garage example? or trick on how it could be done?

**Comment by ahtsan** [comment]
Before looking really into the detail, I guess it complains about two policies having the same name. Try to  make the policies having different name?

**Comment by krzentner** [comment]
Thanks for taking an interest in Garage! I think Anson's analysis is right. When using TensorFlow, each policy constructs variables under a scope named after its `name` parameter. If you have multiple policy instances in TensorFlow, you need to give each one a unique name when they are constructed.

For example:
```python
        policy = CategoricalMLPPolicy(name='policy', env_spec=env.spec, hidden_sizes=(32, 32))
        machine_policy = CategoricalMLPPolicy(name='machine_policy', env_spec=env.spec, hidden_sizes=(32, 32))
        machine_player = MachinePlayer(..., policy=machine_policy, ...)
```

Note that if you need to make two policies the same, you can copy parameters from one to another using:
```python
    machine_policy.set_param_values(policy.get_param_values())
```

**Comment by krzentner** [comment]
I'm going to close this issue, because I believe this has addressed your issue, but feel free to re-open if it does not.

**Comment by mdalvi** [comment]
@krzentner @ahtsan 
Unfortunately changing name does not work! 

Also ,
`machine_policy.set_param_values(policy.get_param_values())`
executing above code would need both the policies instantiated. But the error happens during second installation, so not possible!

**Comment by ahtsan** [comment]
@mdalvi Can you put a breakpoint right before you instantiate the second policy, and see what `tf.global_variables()` gives you? Does a policy exists with the same name as the second policy?

**Comment by mdalvi** [comment]
@ahtsan 
Here is the tf.global_variables() output,

`tf.global_variables() [<tf.Variable 'policy/MLPModel/mlp/hidden_0/kernel:0' shape=(17, 32) dtype=float32_ref>, <tf.Variable 'policy/MLPModel/mlp/hidden_0/bias:0' shape=(32,) dtype=float32_ref>, <tf.Variable 'policy/MLPModel/mlp/hidden_1/kernel:0' shape=(32, 32) dtype=float32_ref>, <tf.Variable 'policy/MLPModel/mlp/hidden_1/bias:0' shape=(32,) dtype=float32_ref>, <tf.Variable 'policy/MLPModel/mlp/output/kernel:0' shape=(32, 2) dtype=float32_ref>, <tf.Variable 'policy/MLPModel/mlp/output/bias:0' shape=(2,) dtype=float32_ref>]`

with the main code,

```
class Simulator(Engine):
    def __init__(self, args):
        super(Simulator, self).__init__()
        self.args = args
        
    def run(self):
        run_experiment(self.run_task, snapshot_mode="last", seed=1, force_cpu=True)
    
    def run_task(self, snapshot_config, variant, *_):
        with LocalTFRunner(snapshot_config=snapshot_config) as runner:
            config = Config()
            config.initialize(Path(f'config/templates/{self.args.config}'))
        
            experiment = joblib.load(Path('data/local/experiment/experiment_2020_04_17_01_19_55_0001/params.pkl'))
            old_policy = experiment['algo'].policy
            print('Loading old_policy completed successfully...', old_policy)
            print('tf.global_variables()', tf.global_variables())
        
            env = TfEnv(env=Poker(self.args, config, old_policy))
        
            policy = CategoricalMLPPolicy(name='new_policy', env_spec=env.spec, hidden_sizes=(32, 32))
            baseline = LinearFeatureBaseline(env_spec=env.spec)
            algorithm = TRPO(env_spec=env.spec, policy=policy, baseline=baseline, max_path_length=100, discount=0.99,
                             max_kl_step=0.01)
        
            runner.setup(algorithm, env)
            runner.train(n_epochs=100, batch_size=256)
```
Yet the error remains same,
`ValueError: Variable policy/MLPModel/mlp/hidden_0/kernel already exists, disallowed. Did you mean to set reuse=True or reuse=tf.AUTO_REUSE in VarScope? Originally defined at:`

**Comment by mdalvi** [comment]
Also, I am a bit surprised that I cannot reproduce the error with below **modified CartPole TRPO** example, 

```
import joblib
import tensorflow as tf
from garage.experiment import run_experiment
from garage.np.baselines import LinearFeatureBaseline
from garage.tf.algos import TRPO
from garage.tf.envs import TfEnv
from garage.tf.experiment import LocalTFRunner
from garage.tf.policies import CategoricalMLPPolicy


def run_task(snapshot_config, *_):
    with LocalTFRunner(snapshot_config=snapshot_config) as runner:
        env = TfEnv(env_name='CartPole-v1')

        # below line was used to train saved experiment
        # policy = CategoricalMLPPolicy(name='old_policy', env_spec=env.spec, hidden_sizes=(32, 32))

        # ====================================
        # below part was commented during first run!
        # ====================================
        experiment = joblib.load('data/local/experiment/experiment_2020_04_17_21_32_33_0001/params.pkl')
        old_policy = experiment['algo'].policy
        print('old_policy', old_policy)
        print('tf.global_variables()', tf.global_variables())
        policy = CategoricalMLPPolicy(name='new_policy', env_spec=env.spec, hidden_sizes=(32, 32))
        # ====================================

        baseline = LinearFeatureBaseline(env_spec=env.spec)

        algo = TRPO(env_spec=env.spec, policy=policy, baseline=baseline, max_path_length=100, discount=0.99,
                    max_kl_step=0.01)

        runner.setup(algo, env)
        runner.train(n_epochs=10, batch_size=256)


run_experiment(run_task, snapshot_mode="last", seed=1, force_cpu=True)
```
**_It works perfectly fine!!!_**

**Comment by ahtsan** [comment]
> CategoricalMLPPolicy

Which line triggers the error?

**Comment by ahtsan** [comment]
> @ahtsan
> Here is the tf.global_variables() output,
> 
> `Loading old_policy completed successfully... <garage.tf.policies.categorical_mlp_policy.CategoricalMLPPolicy object at 0x7f5c54402b10> tf.global_variables() [<tf.Variable 'policy/MLPModel/mlp/hidden_0/kernel:0' shape=(17, 32) dtype=float32_ref>, <tf.Variable 'policy/MLPModel/mlp/hidden_0/bias:0' shape=(32,) dtype=float32_ref>, <tf.Variable 'policy/MLPModel/mlp/hidden_1/kernel:0' shape=(32, 32) dtype=float32_ref>, <tf.Variable 'policy/MLPModel/mlp/hidden_1/bias:0' shape=(32,) dtype=float32_ref>, <tf.Variable 'policy/MLPModel/mlp/output/kernel:0' shape=(32, 2) dtype=float32_ref>, <tf.Variable 'policy/MLPModel/mlp/output/bias:0' shape=(2,) dtype=float32_ref>]`
> 
> with the main code,
> 
> ```
> class Simulator(Engine):
>     def __init__(self, args):
>         super(Simulator, self).__init__()
>         self.args = args
>         
>     def run(self):
>         run_experiment(self.run_task, snapshot_mode="last", seed=1, force_cpu=True)
>     
>     def run_task(self, snapshot_config, variant, *_):
>         with LocalTFRunner(snapshot_config=snapshot_config) as runner:
>             config = Config()
>             config.initialize(Path(f'config/templates/{self.args.config}'))
>         
>             experiment = joblib.load(Path('data/local/experiment/experiment_2020_04_17_01_19_55_0001/params.pkl'))
>             old_policy = experiment['algo'].policy
>             print('Loading old_policy completed successfully...', old_policy)
>             print('tf.global_variables()', tf.global_variables())
>         
>             env = TfEnv(env=Poker(self.args, config, old_policy))
>         
>             policy = CategoricalMLPPolicy(name='new_policy', env_spec=env.spec, hidden_sizes=(32, 32))
>             baseline = LinearFeatureBaseline(env_spec=env.spec)
>             algorithm = TRPO(env_spec=env.spec, policy=policy, baseline=baseline, max_path_length=100, discount=0.99,
>                              max_kl_step=0.01)
>         
>             runner.setup(algorithm, env)
>             runner.train(n_epochs=100, batch_size=256)
> ```
> 
> Yet the error remains same,
> `ValueError: Variable policy/MLPModel/mlp/hidden_0/kernel already exists, disallowed. Did you mean to set reuse=True or reuse=tf.AUTO_REUSE in VarScope? Originally defined at:`

Which line triggers the error?

**Comment by mdalvi** [comment]
As per the traceback, 

[Line 83, garage/tf/models/mlp.py](https://github.com/rlworkgroup/garage/blob/master/src/garage/tf/models/mlp.py#L83) 

```
Traceback (most recent call last):
  File "/home/mdalvi/miniconda3/lib/python3.7/site-packages/garage/experiment/local_runner.py", line 279, in step_epochs
    self._start_worker()
  File "/home/mdalvi/miniconda3/lib/python3.7/site-packages/garage/experiment/local_runner.py", line 100, in _start_worker
    self.sampler.start_worker()
  File "/home/mdalvi/miniconda3/lib/python3.7/site-packages/garage/sampler/on_policy_vectorized_sampler.py", line 39, in start_worker
    envs = [pickle.loads(pickle.dumps(self.env)) for _ in range(n_envs)]
  File "/home/mdalvi/miniconda3/lib/python3.7/site-packages/garage/sampler/on_policy_vectorized_sampler.py", line 39, in <listcomp>
    envs = [pickle.loads(pickle.dumps(self.env)) for _ in range(n_envs)]
  File "/home/mdalvi/miniconda3/lib/python3.7/site-packages/garage/tf/policies/categorical_mlp_policy.py", line 141, in __setstate__
    self._initialize()
  File "/home/mdalvi/miniconda3/lib/python3.7/site-packages/garage/tf/policies/categorical_mlp_policy.py", line 83, in _initialize
    self.model.build(state_input)
  File "/home/mdalvi/miniconda3/lib/python3.7/site-packages/garage/tf/models/base.py", line 198, in build
    network._outputs = self._build(*inputs, name)
  File "/home/mdalvi/miniconda3/lib/python3.7/site-packages/garage/tf/models/mlp_model.py", line 75, in _build
    layer_normalization=self._layer_normalization)
  File "/home/mdalvi/miniconda3/lib/python3.7/site-packages/garage/tf/models/mlp.py", line 83, in mlp
    name='hidden_{}'.format(idx))
  File "/home/mdalvi/miniconda3/lib/python3.7/site-packages/tensorflow_core/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/home/mdalvi/miniconda3/lib/python3.7/site-packages/tensorflow_core/python/layers/core.py", line 187, in dense
    return layer.apply(inputs)
  File "/home/mdalvi/miniconda3/lib/python3.7/site-packages/tensorflow_core/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/home/mdalvi/miniconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 1700, in apply
    return self.__call__(inputs, *args, **kwargs)
  File "/home/mdalvi/miniconda3/lib/python3.7/site-packages/tensorflow_core/python/layers/base.py", line 548, in __call__
    outputs = super(Layer, self).__call__(inputs, *args, **kwargs)
  File "/home/mdalvi/miniconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 824, in __call__
    self._maybe_build(inputs)
  File "/home/mdalvi/miniconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 2146, in _maybe_build
    self.build(input_shapes)
  File "/home/mdalvi/miniconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/layers/core.py", line 1021, in build
    trainable=True)
  File "/home/mdalvi/miniconda3/lib/python3.7/site-packages/tensorflow_core/python/layers/base.py", line 461, in add_weight
    **kwargs)
  File "/home/mdalvi/miniconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 529, in add_weight
    aggregation=aggregation)
  File "/home/mdalvi/miniconda3/lib/python3.7/site-packages/tensorflow_core/python/training/tracking/base.py", line 712, in _add_variable_with_custom_getter
    **kwargs_for_getter)
  File "/home/mdalvi/miniconda3/lib/python3.7/site-packages/tensorflow_core/python/ops/variable_scope.py", line 1500, in get_variable
    aggregation=aggregation)
  File "/home/mdalvi/miniconda3/lib/python3.7/site-packages/tensorflow_core/python/ops/variable_scope.py", line 1243, in get_variable
    aggregation=aggregation)
  File "/home/mdalvi/miniconda3/lib/python3.7/site-packages/tensorflow_core/python/ops/variable_scope.py", line 567, in get_variable
    aggregation=aggregation)
  File "/home/mdalvi/miniconda3/lib/python3.7/site-packages/tensorflow_core/python/ops/variable_scope.py", line 519, in _true_getter
    aggregation=aggregation)
  File "/home/mdalvi/miniconda3/lib/python3.7/site-packages/tensorflow_core/python/ops/variable_scope.py", line 868, in _get_single_variable
    (err_msg, "".join(traceback.format_list(tb))))
ValueError: Variable policy/MLPModel/mlp/hidden_0/kernel already exists, disallowed. Did you mean to set reuse=True or reuse=tf.AUTO_REUSE in VarScope? Originally defined at:

  File "/home/mdalvi/miniconda3/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()
  File "/home/mdalvi/miniconda3/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "/home/mdalvi/miniconda3/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "/home/mdalvi/miniconda3/lib/python3.7/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/mdalvi/miniconda3/lib/python3.7/site-packages/tensorflow_core/python/framework/op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mdalvi/miniconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/mdalvi/miniconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/mdalvi/miniconda3/lib/python3.7/site-packages/garage/experiment/experiment_wrapper.py", line 251, in <module>
    run_experiment(sys.argv)
  File "/home/mdalvi/miniconda3/lib/python3.7/site-packages/garage/experiment/experiment_wrapper.py", line 166, in run_experiment
    args.resume_from_epoch)
  File "/home/mdalvi/Documents/poker-assistant/engine/simulator.py", line 74, in run_task
    runner.train(n_epochs=100, batch_size=256)
  File "/home/mdalvi/miniconda3/lib/python3.7/site-packages/garage/experiment/local_runner.py", line 255, in train
    return self.algo.train(self)
  File "/home/mdalvi/miniconda3/lib/python3.7/site-packages/garage/tf/algos/batch_polopt.py", line 92, in train
    for epoch in runner.step_epochs():
  File "/home/mdalvi/miniconda3/lib/python3.7/site-packages/garage/experiment/local_runner.py", line 300, in step_epochs
    self._shutdown_worker()
  File "/home/mdalvi/miniconda3/lib/python3.7/site-packages/garage/experiment/local_runner.py", line 108, in _shutdown_worker
    self.sampler.shutdown_worker()
  File "/home/mdalvi/miniconda3/lib/python3.7/site-packages/garage/sampler/on_policy_vectorized_sampler.py", line 50, in shutdown_worker
    self.vec_env.close()
AttributeError: 'NoneType' object has no attribute 'close'
```

**Comment by ahtsan** [comment]
Ok I see the reason now -- You are loading the policy during environment instantiation, which get called multiple times when environments are copied for parallel sampling. Can you try decoupling the policy with the environment? i.e. the policy should not be owned by the environment.

**Comment by mdalvi** [comment]
> Ok I see the reason now -- You are loading the policy during environment instantiation, which get called multiple times when environments are copied for parallel sampling. Can you try decoupling the policy with the environment? i.e. the policy should not be owned by the environment.

Give me some time, I need to return a flag from the environment in that case in order to identify the policy to act with!

**Comment by ryanjulian** [comment]
@ahtsan alternatively, he could update the pickle implementation of his environment to create a new policy with a different scope. it's less-efficient, but should work.

**Comment by krzentner** [comment]
Yeah, probably the simplest way of fixing this is to construct a random tensorflow variable scope every time the environment is unpickled. Basically, adding two methods like this to the environment:
```python
def __getstate__(self):
    state = self.__dict__.copy()
    state['policy'] = pickle.dumps(state['policy'])
    return state

def __setstate__(self, state):
    self.__dict__ = state
    with tf.compat.v1.variable_scope("policy{}".format(random.randrange(1e9))):
        self.policy = pickle.loads(self.policy)
```

Note the above might not be perfectly correct; it's hard for me to debug without all of the code.
Alternatively, using the `RaySampler` will likely fix this issue, since each env instance will be in a separate process.

**Comment by krzentner** [comment]
The sampler being used above (`garage.sampler.OnPolicyVectorizedSampler`) constructs multiple environments. As Anson points out, this is what's actually causing the crash, since all of those environments try to construct the same policy in the same variable scope.

I think it's fine for the environment to own the policy (conceptually, it's what you want to do), but if so the environment instances either need to have separate variable scopes (as I describe above), or the environment instances need to be in separate processes.

This can be achieved by using a different sampler, which uses one environment per process:
```python
from garage.sampler import RaySampler

...

    runner.setup(algorithm, env, sampler_cls=RaySampler)
```

Or, if that doesn't work:
```python
from garage.tf.sampler import BatchSampler

...

    runner.setup(algorithm, env, sampler_cls=BatchSampler)
```

Which I realize now is probably easier to do than the above comment.

**Comment by mdalvi** [comment]
Thank you, @ahtsan @krzentner 
```
runner.setup(algorithm, env, sampler_cls=BatchSampler)
```
`BatchSamlpler `comes at rescue,

Here is the implementation code,
```
class Simulator(Engine):
    def __init__(self, args):
        super(Simulator, self).__init__()
        self.args = args

    def run(self):
        run_experiment(self.run_task, snapshot_mode="last", seed=1, force_cpu=True)

    def run_task(self, snapshot_config, variant, *_):
        with LocalTFRunner(snapshot_config=snapshot_config) as runner:
            config = Config()
            config.initialize(Path(f'config/templates/{self.args.config}'))

            exp_path = 'data/local/experiment/experiment_2020_04_18_05_07_57_0001/params.pkl'
            experiment = joblib.load(Path(exp_path))
            old_policy = experiment['algo'].policy
            print("Loading old policy completed...{}".format(old_policy))

            env = TfEnv(env=Poker(self.args, config, old_policy))

            policy = CategoricalMLPPolicy(name=f'p_{datetime.now().strftime("%Y%m%d%H%M%S")}', env_spec=env.spec,
                                          hidden_nonlinearity=tf.nn.relu, hidden_sizes=(64, 64))
            baseline = LinearFeatureBaseline(env_spec=env.spec)
            algorithm = TRPO(env_spec=env.spec, policy=policy, baseline=baseline, max_path_length=100, discount=0.99,
                             max_kl_step=0.01)

            runner.setup(algorithm, env, sampler_cls=BatchSampler)
            runner.train(n_epochs=150, batch_size=256)
```

If above, didn't had worked my ultimate through was to generate a `HTTP request` to `localhost` Flask or Tornado server script hosting old_policy with `state` as JSON and return `action` from the same!

@ryanjulian 
Yes I will get you a 1vs1 player example, sure. Give me some time on that.
