### ISSUE TITLE
spec() wrapper should return garage.spaces types, not gym.spaces types

### ISSUE THREAD

**Issue by ryanjulian** [rlworkgroup/garage#133]
https://github.com/rlworkgroup/garage/blob/master/garage/envs/util.py#L113

**Comment by ryanjulian** [comment]
This has broken the TF tree (and presumably theano too)

**Comment by ryanjulian** [comment]
Well tip-of-tree is broken for all of tf (and probably theano). This should never happen. We will make arbitrarily large changes to make it unbroken, including rewriting all of spec or spaces.

**Comment by ryanjulian** [comment]
```sh
(garage) rjulian@nyquist:~/code/garage$ python garage/tf/launchers/trpo_cartpole.py
2018-07-06 14:45:51.821318: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
2018-07-06 14:45:52.155930: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1356] Found device 0 with properties: 
name: TITAN Xp major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:17:00.0
totalMemory: 11.91GiB freeMemory: 11.52GiB
2018-07-06 14:45:52.468052: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1356] Found device 1 with properties: 
name: TITAN Xp major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:65:00.0
totalMemory: 11.91GiB freeMemory: 11.52GiB
2018-07-06 14:45:52.745682: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1356] Found device 2 with properties: 
name: GeForce GTX 1060 6GB major: 6 minor: 1 memoryClockRate(GHz): 1.7085
pciBusID: 0000:b3:00.0
totalMemory: 5.92GiB freeMemory: 4.72GiB
2018-07-06 14:45:52.746130: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1435] Adding visible gpu devices: 0, 1, 2
2018-07-06 14:45:53.330778: I tensorflow/core/common_runtime/gpu/gpu_device.cc:923] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-07-06 14:45:53.330815: I tensorflow/core/common_runtime/gpu/gpu_device.cc:929]      0 1 2 
2018-07-06 14:45:53.330823: I tensorflow/core/common_runtime/gpu/gpu_device.cc:942] 0:   N Y N 
2018-07-06 14:45:53.330830: I tensorflow/core/common_runtime/gpu/gpu_device.cc:942] 1:   Y N N 
2018-07-06 14:45:53.330836: I tensorflow/core/common_runtime/gpu/gpu_device.cc:942] 2:   N N N 
2018-07-06 14:45:53.331310: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1053] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 11154 MB memory) -> physical GPU (device: 0, name: TITAN Xp, pci bus id: 0000:17:00.0, compute capability: 6.1)
2018-07-06 14:45:53.432040: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1053] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 11154 MB memory) -> physical GPU (device: 1, name: TITAN Xp, pci bus id: 0000:65:00.0, compute capability: 6.1)
2018-07-06 14:45:53.536761: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1053] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:2 with 4482 MB memory) -> physical GPU (device: 2, name: GeForce GTX 1060 6GB, pci bus id: 0000:b3:00.0, compute capability: 6.1)
2018-07-06 14:45:53.764346 PDT | itr #0 | Obtaining samples...
2018-07-06 14:45:53.764537 PDT | itr #0 | Obtaining samples for iteration 0...
0% [##############################] 100% | ETA: 00:00:00
Total time elapsed: 00:00:01
2018-07-06 14:45:55.148759 PDT | itr #0 | Processing samples...
2018-07-06 14:45:55.164158 PDT | itr #0 | fitting baseline...
2018-07-06 14:45:55.190022 PDT | itr #0 | fitted
2018-07-06 14:45:55.191037 PDT | itr #0 | Logging diagnostics...
2018-07-06 14:45:55.192601 PDT | itr #0 | Optimizing policy...
2018-07-06 14:45:55.192809 PDT | itr #0 | Computing loss before
2018-07-06 14:45:55.231854 PDT | itr #0 | Computing KL before
2018-07-06 14:45:55.271742 PDT | itr #0 | Optimizing
2018-07-06 14:45:55.282165 PDT | itr #0 | Start CG optimization: #parameters: 1250, #inputs: 4019, #subsample_inputs: 4019
2018-07-06 14:45:55.282315 PDT | itr #0 | computing loss before
2018-07-06 14:45:55.284227 PDT | itr #0 | performing update
2018-07-06 14:45:55.284363 PDT | itr #0 | computing gradient
2018-07-06 14:45:55.357467 PDT | itr #0 | gradient computed
2018-07-06 14:45:55.357651 PDT | itr #0 | computing descent direction
2018-07-06 14:45:56.315219 PDT | itr #0 | descent direction computed
2018-07-06 14:45:56.410310 PDT | itr #0 | backtrack iters: 2
2018-07-06 14:45:56.410654 PDT | itr #0 | computing loss after
2018-07-06 14:45:56.410884 PDT | itr #0 | optimization finished
2018-07-06 14:45:56.411114 PDT | itr #0 | Computing KL after
2018-07-06 14:45:56.413468 PDT | itr #0 | Computing loss after
2018-07-06 14:45:56.416646 PDT | itr #0 | Saving snapshot...
2018-07-06 14:45:56.416941 PDT | itr #0 | Saved
2018-07-06 14:45:56.418436 PDT | -----------------------  -------------
2018-07-06 14:45:56.418698 PDT | AverageDiscountedReturn   59.0333
2018-07-06 14:45:56.418918 PDT | AveragePolicyStd           1
2018-07-06 14:45:56.419130 PDT | AverageReturn             61.7262
2018-07-06 14:45:56.419350 PDT | Entropy                    1.41894
2018-07-06 14:45:56.419548 PDT | EnvExecTime                1.07171
2018-07-06 14:45:56.419745 PDT | ExplainedVariance          5.14133e-12
2018-07-06 14:45:56.419942 PDT | Iteration                  0
2018-07-06 14:45:56.420140 PDT | ItrTime                    2.65294
2018-07-06 14:45:56.420342 PDT | LossAfter                 -0.0358085
2018-07-06 14:45:56.420537 PDT | LossBefore                -6.64416e-09
2018-07-06 14:45:56.420734 PDT | MaxReturn                349.849
2018-07-06 14:45:56.420929 PDT | MeanKL                     0.0094394
2018-07-06 14:45:56.421125 PDT | MeanKLBefore               0
2018-07-06 14:45:56.421370 PDT | MinReturn                  0
2018-07-06 14:45:56.421566 PDT | NumTrajs                 560
2018-07-06 14:45:56.421762 PDT | Perplexity                 4.13273
2018-07-06 14:45:56.421963 PDT | PolicyExecTime             0.277727
2018-07-06 14:45:56.422157 PDT | ProcessExecTime            0.0252109
2018-07-06 14:45:56.422353 PDT | StdReturn                 49.1782
2018-07-06 14:45:56.422555 PDT | Time                       2.65286
2018-07-06 14:45:56.422749 PDT | dLoss                      0.0358085
2018-07-06 14:45:56.422969 PDT | -----------------------  -------------
2018-07-06 14:45:56.424501 PDT | itr #1 | Obtaining samples...
2018-07-06 14:45:56.424661 PDT | itr #1 | Obtaining samples for iteration 1...
0% [##                            ] 100% | ETA: 00:00:03Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/rjulian/miniconda2/envs/garage/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/home/rjulian/miniconda2/envs/garage/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/rjulian/code/garage/garage/tf/plotter/plotter.py", line 89, in _start_worker
    speedup=5)
  File "/home/rjulian/miniconda2/envs/garage/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/rjulian/miniconda2/envs/garage/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 5060, in get_controller
    yield default
  File "/home/rjulian/code/garage/garage/tf/plotter/plotter.py", line 89, in _start_worker
    speedup=5)
  File "/home/rjulian/miniconda2/envs/garage/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/rjulian/miniconda2/envs/garage/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 5265, in get_controller
    yield g
  File "/home/rjulian/miniconda2/envs/garage/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/rjulian/miniconda2/envs/garage/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 5060, in get_controller
    yield default
  File "/home/rjulian/miniconda2/envs/garage/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 5265, in get_controller
    yield g
  File "/home/rjulian/code/garage/garage/tf/plotter/plotter.py", line 81, in _start_worker
    speedup=5)
  File "/home/rjulian/code/garage/garage/sampler/utils.py", line 30, in rollout
    observations.append(flatten(env.observation_space, o))
  File "/home/rjulian/code/garage/garage/envs/util.py", line 55, in flatten
    raise NotImplementedError
NotImplementedError

0% [##############################] 100% | ETA: 00:00:00
```
