### ISSUE TITLE
Can't run examples/theano/trpo_cartpole_pickled.py on Mac

### ISSUE THREAD

**Issue by jonashen** [rlworkgroup/garage#171]
It was able to run when it was located at `examples/trpo_cartpole_pickled.py`.
Now, at `examples/theano/trpo_cartpole_pickled.py`, there is an unknown threading error.

**Comment by ryanjulian** [comment]
Can you be more specific about the error?

**Comment by jonashen** [comment]
On mac, I get:
```
libc++abi.dylib: terminating with uncaught exception of type std::__1::system_error: thread::join failed: No such process
```
On linux, it starts to run but then the program stops outputting anything (sort of like if you're stuck in a while loop).

**Comment by ryanjulian** [comment]
Is there a backtrace?

**Comment by jonashen** [comment]
not sure what you mean

**Comment by ryanjulian** [comment]
e.g.
```sh
Traceback (most recent call last):
  File "/home/rjulian/miniconda2/envs/garage/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/home/rjulian/miniconda2/envs/garage/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/rjulian/miniconda2/envs/garage/lib/python3.5/multiprocessing/pool.py", line 108, in worker
    task = get()
  File "/home/rjulian/miniconda2/envs/garage/lib/python3.5/site-packages/joblib/pool.py", line 362, in get
    return recv()
  File "/home/rjulian/miniconda2/envs/garage/lib/python3.5/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/home/rjulian/miniconda2/envs/garage/lib/python3.5/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/home/rjulian/miniconda2/envs/garage/lib/python3.5/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
```

**Comment by jonashen** [comment]
No, on mac I just get 
```
2018-07-11 11:53:06.296841 PDT | [experiment_2018_07_11_11_53_00_0001] Populating workers...
libc++abi.dylib: terminating with uncaught exception of type std::__1::system_error: thread::join failed: No such process
libc++abi.dylib: terminating with uncaught exception of type std::__1::system_error: thread::join failed: No such process
libc++abi.dylib: terminating with uncaught exception of type std::__1::system_error: thread::join failed: No such process
...(repeating forever)
```

**Comment by jonashen** [comment]
Linux actually worked for me just now (the wait was just longer than expected). So this is now a Mac issue.

**Comment by ryanjulian** [comment]
This might be a joblib bug. Speculatively, someone might be calling .join() on a process which hasn't been spawned yet.

**Comment by ryanjulian** [comment]
@jonashen is this fixed?

**Comment by jonashen** [comment]
I reran it and it works. Closing now.
