### ISSUE TITLE
tests.test_baselines failed

### ISSUE THREAD

**Issue by hjzh4** [rlworkgroup/garage#183]
```
nose2 tests.test_baselines
```
```
EEE
======================================================================
ERROR: tests.test_baselines.test_baseline:1
<class 'garage.baselines.zero_baseline.ZeroBaseline'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/hejia/Projects/garage/tests/test_baselines.py", line 19, in test_baseline
    policy = GaussianMLPPolicy(env_spec=env.spec, hidden_sizes=(6, ))
  File "/home/hejia/Projects/garage/garage/policies/gaussian_mlp_policy.py", line 56, in __init__
    assert isinstance(env_spec.action_space, Box)
AttributeError: 'NoneType' object has no attribute 'action_space'

======================================================================
ERROR: tests.test_baselines.test_baseline:2
<class 'garage.baselines.linear_feature_baseline.LinearFeatureBaseline'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/hejia/Projects/garage/tests/test_baselines.py", line 19, in test_baseline
    policy = GaussianMLPPolicy(env_spec=env.spec, hidden_sizes=(6, ))
  File "/home/hejia/Projects/garage/garage/policies/gaussian_mlp_policy.py", line 56, in __init__
    assert isinstance(env_spec.action_space, Box)
AttributeError: 'NoneType' object has no attribute 'action_space'

======================================================================
ERROR: tests.test_baselines.test_baseline:3
<class 'garage.baselines.gaussian_mlp_baseline.GaussianMLPBaseline'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/hejia/Projects/garage/tests/test_baselines.py", line 19, in test_baseline
    policy = GaussianMLPPolicy(env_spec=env.spec, hidden_sizes=(6, ))
  File "/home/hejia/Projects/garage/garage/policies/gaussian_mlp_policy.py", line 56, in __init__
    assert isinstance(env_spec.action_space, Box)
AttributeError: 'NoneType' object has no attribute 'action_space'

----------------------------------------------------------------------
Ran 3 tests in 0.047s

FAILED (errors=3)
```

**Comment by jonashen** [comment]
Fixed
