### ISSUE TITLE
PEARL doesn't conform to TrajectoryBatch

### ISSUE THREAD

**Issue by songanz** [rlworkgroup/garage#1865]
Hi, 

Thank you very much for building this fantastic repo. I am really interested in the PEARL meta RL algorithm and I would like to try it in my environment. However, when I successfully implement my environment, I got an error from `/garage/torch/algos/pearl.py --> rollout` function. It says the agent_infos's (I guess that is where you pass the context) size not match the length of the observation.

> Traceback (most recent call last):
  File "/home/songanz/pycharm-2018.3.3/helpers/pydev/pydevd.py", line 1758, in <module>
    main()
  File "/home/songanz/pycharm-2018.3.3/helpers/pydev/pydevd.py", line 1752, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/songanz/pycharm-2018.3.3/helpers/pydev/pydevd.py", line 1147, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/songanz/pycharm-2018.3.3/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/songanz/Documents/Git_repo/highway-pearl/pearl-highway.py", line 164, in <module>
    pearl_half_cheetah_vel()
  File "/home/songanz/Documents/Git_repo/garage/venv/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/songanz/Documents/Git_repo/garage/venv/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/songanz/Documents/Git_repo/garage/venv/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/songanz/Documents/Git_repo/garage/venv/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/songanz/Documents/Git_repo/highway-pearl/garage/experiment/experiment.py", line 362, in __call__
    result = self.function(ctxt, **kwargs)
  File "/home/songanz/Documents/Git_repo/highway-pearl/pearl-highway.py", line 161, in pearl_half_cheetah_vel
    runner.train(n_epochs=num_epochs, batch_size=batch_size)
  File "/home/songanz/Documents/Git_repo/highway-pearl/garage/experiment/local_runner.py", line 502, in train
    average_return = self._algo.train(self)
  File "/home/songanz/Documents/Git_repo/highway-pearl/garage/torch/algos/pearl.py", line 274, in train
    self._num_initial_steps, np.inf)
  File "/home/songanz/Documents/Git_repo/highway-pearl/garage/torch/algos/pearl.py", line 430, in _obtain_samples
    self._env[self._task_idx])
  File "/home/songanz/Documents/Git_repo/highway-pearl/garage/experiment/local_runner.py", line 360, in obtain_samples
    env_update)
  File "/home/songanz/Documents/Git_repo/highway-pearl/garage/experiment/local_runner.py", line 327, in obtain_trajectories
    env_update=env_update)
  File "/home/songanz/Documents/Git_repo/highway-pearl/garage/sampler/local_sampler.py", line 116, in obtain_samples
    batch = worker.rollout()
  File "/home/songanz/Documents/Git_repo/highway-pearl/garage/torch/algos/pearl.py", line 784, in rollout
    return self.collect_rollout()
  File "/home/songanz/Documents/Git_repo/highway-pearl/garage/sampler/default_worker.py", line 170, in collect_rollout
    lengths=np.asarray(lengths, dtype='i'))
  File "/home/songanz/Documents/Git_repo/highway-pearl/garage/_dtypes.py", line 220, in __new__
    format(inferred_batch_size, key, val.shape[0]))
ValueError: Each entry in agent_infos must have a batch dimension of length 12, but got key context with batch size 200 instead.

I think the reason is: my environment will close if the agent goes too wrong or reach the goal. But in the function rollout, agent_infos is defined as:

`self._agent_infos['context'] = [self.agent.z.detach().cpu().numpy()] *self._max_episode_length`
Therefore, the length of the agent_infos is **max_episode_length**. Is there a way to fix it?

**Comment by ryanjulian** [comment]
@songanz Thanks for the report!

You found a bug which we will fix in the next couple weeks.

In the meantime, you can get past this by simple commenting out Lines 207-220 here: https://github.com/rlworkgroup/garage/blob/master/src/garage/_dtypes.py#L207

**Comment by krzentner** [comment]
This is now [fixed on master](https://github.com/rlworkgroup/garage/commit/40381138f89c2e1e6653c5ba628f93b637ee8143#diff-c29608150796624cb681bd3f286e83f9L765), but needs to be backported still.
