### ISSUE TITLE
Master branch can't pass make test

### ISSUE THREAD

**Issue by zequnyu** [rlworkgroup/garage#654]
Current master branch can't pass `make test`. However the failed tests will pass when running unittest separately.

```
======================================================================
ERROR: test_dm_control_tf_policy (tests.garage.envs.dm_control.test_dm_control_tf_policy.TestDmControlTfPolicy)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/code/garage/tests/garage/envs/dm_control/test_dm_control_tf_policy.py", line 38, in test_dm_control_tf_policy
    runner.train(n_epochs=1, batch_size=10)
  File "/root/code/garage/garage/experiment/local_tf_runner.py", line 321, in train
    start_epoch=0)
  File "/root/code/garage/garage/experiment/local_tf_runner.py", line 407, in _train
    self.save(epoch, paths if store_paths else None)
  File "/root/code/garage/garage/experiment/local_tf_runner.py", line 210, in save
    snapshotter.save_itr_params(epoch, params)
  File "/root/code/garage/garage/logger/snapshotter.py", line 85, in save_itr_params
    with open(file_name, 'wb') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpgplyc983/params.pkl'

======================================================================
ERROR: test_cem_cartpole (tests.garage.np.algos.test_cem.TestCEM)
Test CEM with Cartpole-v1 environment.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/code/garage/tests/garage/np/algos/test_cem.py", line 35, in test_cem_cartpole
    n_epochs=5, batch_size=2000, n_epoch_cycles=n_samples)
  File "/root/code/garage/garage/experiment/local_tf_runner.py", line 321, in train
    start_epoch=0)
  File "/root/code/garage/garage/experiment/local_tf_runner.py", line 407, in _train
    self.save(epoch, paths if store_paths else None)
  File "/root/code/garage/garage/experiment/local_tf_runner.py", line 210, in save
    snapshotter.save_itr_params(epoch, params)
  File "/root/code/garage/garage/logger/snapshotter.py", line 85, in save_itr_params
    with open(file_name, 'wb') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpgplyc983/params.pkl'

======================================================================
ERROR: test_cma_es_cartpole (tests.garage.np.algos.test_cma_es.TestCMAES)
Test CMAES with Cartpole-v1 environment.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/code/garage/tests/garage/np/algos/test_cma_es.py", line 33, in test_cma_es_cartpole
    runner.train(n_epochs=1, batch_size=1000, n_epoch_cycles=n_samples)
  File "/root/code/garage/garage/experiment/local_tf_runner.py", line 321, in train
    start_epoch=0)
  File "/root/code/garage/garage/experiment/local_tf_runner.py", line 407, in _train
    self.save(epoch, paths if store_paths else None)
  File "/root/code/garage/garage/experiment/local_tf_runner.py", line 210, in save
    snapshotter.save_itr_params(epoch, params)
  File "/root/code/garage/garage/logger/snapshotter.py", line 85, in save_itr_params
    with open(file_name, 'wb') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpgplyc983/params.pkl'

======================================================================
FAIL: test_trpo_recurrent_cartpole (tests.garage.tf.algos.test_trpo_with_model.TestTRPO)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/code/garage/tests/garage/tf/algos/test_trpo_with_model.py", line 39, in test_trpo_recurrent_cartpole
    assert last_avg_ret > 90
AssertionError

----------------------------------------------------------------------
Ran 623 tests in 789.240s

FAILED (failures=1, errors=3)
Makefile:60: recipe for target 'run-headless' failed
make: *** [run-headless] Error 1
```

**Comment by ryanjulian** [comment]
#651 should fix the last error.

@zequnyu can you debug the other 3? they are probably related to the snapshotter and/or experiment runner.

**Comment by gitanshu** [comment]
Similar issue with more tests on work machine 

<details>
<summary>Logs</summary>
======================================================================
ERROR: test_cem_cartpole (tests.garage.np.algos.test_cem.TestCEM)
Test CEM with Cartpole-v1 environment.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/code/garage/tests/garage/np/algos/test_cem.py", line 35, in test_cem_cartpole
    n_epochs=5, batch_size=2000, n_epoch_cycles=n_samples)
  File "/root/code/garage/garage/experiment/local_tf_runner.py", line 321, in train
    start_epoch=0)
  File "/root/code/garage/garage/experiment/local_tf_runner.py", line 407, in _train
    self.save(epoch, paths if store_paths else None)
  File "/root/code/garage/garage/experiment/local_tf_runner.py", line 210, in save
    snapshotter.save_itr_params(epoch, params)
  File "/root/code/garage/garage/experiment/snapshotter.py", line 86, in save_itr_params
    with open(file_name, 'wb') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpc4b1c6zj/params.pkl'

======================================================================
ERROR: test_cma_es_cartpole (tests.garage.np.algos.test_cma_es.TestCMAES)
Test CMAES with Cartpole-v1 environment.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/code/garage/tests/garage/np/algos/test_cma_es.py", line 33, in test_cma_es_cartpole
    runner.train(n_epochs=1, batch_size=1000, n_epoch_cycles=n_samples)
  File "/root/code/garage/garage/experiment/local_tf_runner.py", line 321, in train
    start_epoch=0)
  File "/root/code/garage/garage/experiment/local_tf_runner.py", line 407, in _train
    self.save(epoch, paths if store_paths else None)
  File "/root/code/garage/garage/experiment/local_tf_runner.py", line 210, in save
    snapshotter.save_itr_params(epoch, params)
  File "/root/code/garage/garage/experiment/snapshotter.py", line 86, in save_itr_params
    with open(file_name, 'wb') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpc4b1c6zj/params.pkl'

======================================================================
ERROR: test_dm_control_tf_policy (tests.garage.envs.dm_control.test_dm_control_tf_policy.TestDmControlTfPolicy)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/code/garage/tests/garage/envs/dm_control/test_dm_control_tf_policy.py", line 38, in test_dm_control_tf_policy
    runner.train(n_epochs=1, batch_size=10)
  File "/root/code/garage/garage/experiment/local_tf_runner.py", line 321, in train
    start_epoch=0)
  File "/root/code/garage/garage/experiment/local_tf_runner.py", line 407, in _train
    self.save(epoch, paths if store_paths else None)
  File "/root/code/garage/garage/experiment/local_tf_runner.py", line 210, in save
    snapshotter.save_itr_params(epoch, params)
  File "/root/code/garage/garage/experiment/snapshotter.py", line 86, in save_itr_params
    with open(file_name, 'wb') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpc4b1c6zj/params.pkl'

======================================================================
ERROR: test_categorical_policies:1
<class 'garage.tf.policies.categorical_gru_policy.CategoricalGRUPolicy'> (tests.garage.tf.policies.test_categorical_policies.TestCategoricalPolicies)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/code/garage/tests/garage/tf/policies/test_categorical_policies.py", line 47, in test_categorical_policies
    runner.train(n_epochs=1, batch_size=4000)
  File "/root/code/garage/garage/experiment/local_tf_runner.py", line 321, in train
    start_epoch=0)
  File "/root/code/garage/garage/experiment/local_tf_runner.py", line 407, in _train
    self.save(epoch, paths if store_paths else None)
  File "/root/code/garage/garage/experiment/local_tf_runner.py", line 210, in save
    snapshotter.save_itr_params(epoch, params)
  File "/root/code/garage/garage/experiment/snapshotter.py", line 86, in save_itr_params
    with open(file_name, 'wb') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpc4b1c6zj/params.pkl'

======================================================================
ERROR: test_categorical_policies:2
<class 'garage.tf.policies.categorical_lstm_policy.CategoricalLSTMPolicy'> (tests.garage.tf.policies.test_categorical_policies.TestCategoricalPolicies)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/code/garage/tests/garage/tf/policies/test_categorical_policies.py", line 47, in test_categorical_policies
    runner.train(n_epochs=1, batch_size=4000)
  File "/root/code/garage/garage/experiment/local_tf_runner.py", line 321, in train
    start_epoch=0)
  File "/root/code/garage/garage/experiment/local_tf_runner.py", line 407, in _train
    self.save(epoch, paths if store_paths else None)
  File "/root/code/garage/garage/experiment/local_tf_runner.py", line 210, in save
    snapshotter.save_itr_params(epoch, params)
  File "/root/code/garage/garage/experiment/snapshotter.py", line 86, in save_itr_params
    with open(file_name, 'wb') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpc4b1c6zj/params.pkl'

======================================================================
ERROR: test_categorical_policies:3
<class 'garage.tf.policies.categorical_mlp_policy.CategoricalMLPPolicy'> (tests.garage.tf.policies.test_categorical_policies.TestCategoricalPolicies)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/code/garage/tests/garage/tf/policies/test_categorical_policies.py", line 47, in test_categorical_policies
    runner.train(n_epochs=1, batch_size=4000)
  File "/root/code/garage/garage/experiment/local_tf_runner.py", line 321, in train
    start_epoch=0)
  File "/root/code/garage/garage/experiment/local_tf_runner.py", line 407, in _train
    self.save(epoch, paths if store_paths else None)
  File "/root/code/garage/garage/experiment/local_tf_runner.py", line 210, in save
    snapshotter.save_itr_params(epoch, params)
  File "/root/code/garage/garage/experiment/snapshotter.py", line 86, in save_itr_params
    with open(file_name, 'wb') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpc4b1c6zj/params.pkl'

======================================================================
ERROR: test_gaussian_policies:1
<class 'garage.tf.policies.gaussian_gru_policy.GaussianGRUPolicy'> (tests.garage.tf.policies.test_gaussian_policies.TestGaussianPolicies)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/code/garage/tests/garage/tf/policies/test_gaussian_policies.py", line 43, in test_gaussian_policies
    runner.train(n_epochs=1, batch_size=4000)
  File "/root/code/garage/garage/experiment/local_tf_runner.py", line 321, in train
    start_epoch=0)
  File "/root/code/garage/garage/experiment/local_tf_runner.py", line 407, in _train
    self.save(epoch, paths if store_paths else None)
  File "/root/code/garage/garage/experiment/local_tf_runner.py", line 210, in save
    snapshotter.save_itr_params(epoch, params)
  File "/root/code/garage/garage/experiment/snapshotter.py", line 86, in save_itr_params
    with open(file_name, 'wb') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpc4b1c6zj/params.pkl'

======================================================================
ERROR: test_gaussian_policies:2
<class 'garage.tf.policies.gaussian_lstm_policy.GaussianLSTMPolicy'> (tests.garage.tf.policies.test_gaussian_policies.TestGaussianPolicies)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/code/garage/tests/garage/tf/policies/test_gaussian_policies.py", line 43, in test_gaussian_policies
    runner.train(n_epochs=1, batch_size=4000)
  File "/root/code/garage/garage/experiment/local_tf_runner.py", line 321, in train
    start_epoch=0)
  File "/root/code/garage/garage/experiment/local_tf_runner.py", line 407, in _train
    self.save(epoch, paths if store_paths else None)
  File "/root/code/garage/garage/experiment/local_tf_runner.py", line 210, in save
    snapshotter.save_itr_params(epoch, params)
  File "/root/code/garage/garage/experiment/snapshotter.py", line 86, in save_itr_params
    with open(file_name, 'wb') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpc4b1c6zj/params.pkl'

======================================================================
ERROR: test_gaussian_policies:3
<class 'garage.tf.policies.gaussian_mlp_policy.GaussianMLPPolicy'> (tests.garage.tf.policies.test_gaussian_policies.TestGaussianPolicies)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/code/garage/tests/garage/tf/policies/test_gaussian_policies.py", line 43, in test_gaussian_policies
    runner.train(n_epochs=1, batch_size=4000)
  File "/root/code/garage/garage/experiment/local_tf_runner.py", line 321, in train
    start_epoch=0)
  File "/root/code/garage/garage/experiment/local_tf_runner.py", line 407, in _train
    self.save(epoch, paths if store_paths else None)
  File "/root/code/garage/garage/experiment/local_tf_runner.py", line 210, in save
    snapshotter.save_itr_params(epoch, params)
  File "/root/code/garage/garage/experiment/snapshotter.py", line 86, in save_itr_params
    with open(file_name, 'wb') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpc4b1c6zj/params.pkl'

======================================================================
ERROR: test_ddpg_pendulum (tests.garage.tf.algos.test_ddpg.TestDDPG)
Test DDPG with Pendulum environment.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/code/garage/tests/garage/tf/algos/test_ddpg.py", line 52, in test_ddpg_pendulum
    n_epochs=10, n_epoch_cycles=20, batch_size=100)
  File "/root/code/garage/garage/experiment/local_tf_runner.py", line 321, in train
    start_epoch=0)
  File "/root/code/garage/garage/experiment/local_tf_runner.py", line 407, in _train
    self.save(epoch, paths if store_paths else None)
  File "/root/code/garage/garage/experiment/local_tf_runner.py", line 210, in save
    snapshotter.save_itr_params(epoch, params)
  File "/root/code/garage/garage/experiment/snapshotter.py", line 86, in save_itr_params
    with open(file_name, 'wb') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpc4b1c6zj/params.pkl'

======================================================================
ERROR: test_vpg_cartpole (tests.garage.tf.algos.test_vpg.TestVPG)
Test VPG with CartPole-v1 environment.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/code/garage/tests/garage/tf/algos/test_vpg.py", line 31, in test_vpg_cartpole
    last_avg_ret = runner.train(n_epochs=10, batch_size=10000)
  File "/root/code/garage/garage/experiment/local_tf_runner.py", line 321, in train
    start_epoch=0)
  File "/root/code/garage/garage/experiment/local_tf_runner.py", line 407, in _train
    self.save(epoch, paths if store_paths else None)
  File "/root/code/garage/garage/experiment/local_tf_runner.py", line 210, in save
    snapshotter.save_itr_params(epoch, params)
  File "/root/code/garage/garage/experiment/snapshotter.py", line 86, in save_itr_params
    with open(file_name, 'wb') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpc4b1c6zj/params.pkl'

======================================================================
ERROR: test_erwr_cartpole (tests.garage.tf.algos.test_erwr.TestERWR)
Test ERWR with Cartpole-v1 environment.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/code/garage/tests/garage/tf/algos/test_erwr.py", line 29, in test_erwr_cartpole
    last_avg_ret = runner.train(n_epochs=10, batch_size=10000)
  File "/root/code/garage/garage/experiment/local_tf_runner.py", line 321, in train
    start_epoch=0)
  File "/root/code/garage/garage/experiment/local_tf_runner.py", line 407, in _train
    self.save(epoch, paths if store_paths else None)
  File "/root/code/garage/garage/experiment/local_tf_runner.py", line 210, in save
    snapshotter.save_itr_params(epoch, params)
  File "/root/code/garage/garage/experiment/snapshotter.py", line 86, in save_itr_params
    with open(file_name, 'wb') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpc4b1c6zj/params.pkl'

======================================================================
ERROR: test_dqn_cartpole (tests.garage.tf.algos.test_dqn.TestDQN)
Test DQN with CartPole environment.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/code/garage/tests/garage/tf/algos/test_dqn.py", line 57, in test_dqn_cartpole
    batch_size=sampler_batch_size)
  File "/root/code/garage/garage/experiment/local_tf_runner.py", line 321, in train
    start_epoch=0)
  File "/root/code/garage/garage/experiment/local_tf_runner.py", line 407, in _train
    self.save(epoch, paths if store_paths else None)
  File "/root/code/garage/garage/experiment/local_tf_runner.py", line 210, in save
    snapshotter.save_itr_params(epoch, params)
  File "/root/code/garage/garage/experiment/snapshotter.py", line 86, in save_itr_params
    with open(file_name, 'wb') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpc4b1c6zj/params.pkl'

======================================================================
ERROR: test_dqn_cartpole_double_q (tests.garage.tf.algos.test_dqn.TestDQN)
Test DQN with CartPole environment.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/code/garage/tests/garage/tf/algos/test_dqn.py", line 101, in test_dqn_cartpole_double_q
    batch_size=sampler_batch_size)
  File "/root/code/garage/garage/experiment/local_tf_runner.py", line 321, in train
    start_epoch=0)
  File "/root/code/garage/garage/experiment/local_tf_runner.py", line 407, in _train
    self.save(epoch, paths if store_paths else None)
  File "/root/code/garage/garage/experiment/local_tf_runner.py", line 210, in save
    snapshotter.save_itr_params(epoch, params)
  File "/root/code/garage/garage/experiment/snapshotter.py", line 86, in save_itr_params
    with open(file_name, 'wb') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpc4b1c6zj/params.pkl'

======================================================================
ERROR: test_dqn_cartpole_grad_clip (tests.garage.tf.algos.test_dqn.TestDQN)
Test DQN with CartPole environment.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/code/garage/tests/garage/tf/algos/test_dqn.py", line 146, in test_dqn_cartpole_grad_clip
    batch_size=sampler_batch_size)
  File "/root/code/garage/garage/experiment/local_tf_runner.py", line 321, in train
    start_epoch=0)
  File "/root/code/garage/garage/experiment/local_tf_runner.py", line 407, in _train
    self.save(epoch, paths if store_paths else None)
  File "/root/code/garage/garage/experiment/local_tf_runner.py", line 210, in save
    snapshotter.save_itr_params(epoch, params)
  File "/root/code/garage/garage/experiment/snapshotter.py", line 86, in save_itr_params
    with open(file_name, 'wb') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpc4b1c6zj/params.pkl'

======================================================================
ERROR: test_trpo_pendulum (tests.garage.tf.algos.test_trpo.TestTRPO)
Test TRPO with Pendulum environment.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/code/garage/tests/garage/tf/algos/test_trpo.py", line 41, in test_trpo_pendulum
    last_avg_ret = runner.train(n_epochs=10, batch_size=2048)
  File "/root/code/garage/garage/experiment/local_tf_runner.py", line 321, in train
    start_epoch=0)
  File "/root/code/garage/garage/experiment/local_tf_runner.py", line 407, in _train
    self.save(epoch, paths if store_paths else None)
  File "/root/code/garage/garage/experiment/local_tf_runner.py", line 210, in save
    snapshotter.save_itr_params(epoch, params)
  File "/root/code/garage/garage/experiment/snapshotter.py", line 86, in save_itr_params
    with open(file_name, 'wb') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpc4b1c6zj/params.pkl'

======================================================================
ERROR: test_reps_cartpole (tests.garage.tf.algos.test_reps.TestREPS)
Test REPS with gym Cartpole environment.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/code/garage/tests/garage/tf/algos/test_reps.py", line 38, in test_reps_cartpole
    last_avg_ret = runner.train(n_epochs=10, batch_size=4000)
  File "/root/code/garage/garage/experiment/local_tf_runner.py", line 321, in train
    start_epoch=0)
  File "/root/code/garage/garage/experiment/local_tf_runner.py", line 407, in _train
    self.save(epoch, paths if store_paths else None)
  File "/root/code/garage/garage/experiment/local_tf_runner.py", line 210, in save
    snapshotter.save_itr_params(epoch, params)
  File "/root/code/garage/garage/experiment/snapshotter.py", line 86, in save_itr_params
    with open(file_name, 'wb') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpc4b1c6zj/params.pkl'

======================================================================
ERROR: test_tnpg_inverted_pendulum (tests.garage.tf.algos.test_tnpg.TestTNPG)
Test TNPG with InvertedPendulum-v2 environment.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/code/garage/tests/garage/tf/algos/test_tnpg.py", line 33, in test_tnpg_inverted_pendulum
    last_avg_ret = runner.train(n_epochs=10, batch_size=10000)
  File "/root/code/garage/garage/experiment/local_tf_runner.py", line 321, in train
    start_epoch=0)
  File "/root/code/garage/garage/experiment/local_tf_runner.py", line 407, in _train
    self.save(epoch, paths if store_paths else None)
  File "/root/code/garage/garage/experiment/local_tf_runner.py", line 210, in save
    snapshotter.save_itr_params(epoch, params)
  File "/root/code/garage/garage/experiment/snapshotter.py", line 86, in save_itr_params
    with open(file_name, 'wb') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpc4b1c6zj/params.pkl'

======================================================================
ERROR: test_ppo_pendulum_with_model (tests.garage.tf.algos.test_ppo_with_models.TestPPOWithModel)
Test PPO with model, with Pendulum environment.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/code/garage/tests/garage/tf/algos/test_ppo_with_models.py", line 42, in test_ppo_pendulum_with_model
    last_avg_ret = runner.train(n_epochs=10, batch_size=2048)
  File "/root/code/garage/garage/experiment/local_tf_runner.py", line 321, in train
    start_epoch=0)
  File "/root/code/garage/garage/experiment/local_tf_runner.py", line 407, in _train
    self.save(epoch, paths if store_paths else None)
  File "/root/code/garage/garage/experiment/local_tf_runner.py", line 210, in save
    snapshotter.save_itr_params(epoch, params)
  File "/root/code/garage/garage/experiment/snapshotter.py", line 86, in save_itr_params
    with open(file_name, 'wb') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpc4b1c6zj/params.pkl'

======================================================================
ERROR: test_ppo_pendulum (tests.garage.tf.algos.test_ppo.TestPPO)
Test PPO with Pendulum environment.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/code/garage/tests/garage/tf/algos/test_ppo.py", line 41, in test_ppo_pendulum
    last_avg_ret = runner.train(n_epochs=10, batch_size=2048)
  File "/root/code/garage/garage/experiment/local_tf_runner.py", line 321, in train
    start_epoch=0)
  File "/root/code/garage/garage/experiment/local_tf_runner.py", line 407, in _train
    self.save(epoch, paths if store_paths else None)
  File "/root/code/garage/garage/experiment/local_tf_runner.py", line 210, in save
    snapshotter.save_itr_params(epoch, params)
  File "/root/code/garage/garage/experiment/snapshotter.py", line 86, in save_itr_params
    with open(file_name, 'wb') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpc4b1c6zj/params.pkl'

======================================================================
ERROR: test_ppo_pendulum_recurrent (tests.garage.tf.algos.test_ppo.TestPPO)
Test PPO with Pendulum environment and recurrent policy.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/code/garage/tests/garage/tf/algos/test_ppo.py", line 66, in test_ppo_pendulum_recurrent
    last_avg_ret = runner.train(n_epochs=10, batch_size=2048)
  File "/root/code/garage/garage/experiment/local_tf_runner.py", line 321, in train
    start_epoch=0)
  File "/root/code/garage/garage/experiment/local_tf_runner.py", line 407, in _train
    self.save(epoch, paths if store_paths else None)
  File "/root/code/garage/garage/experiment/local_tf_runner.py", line 210, in save
    snapshotter.save_itr_params(epoch, params)
  File "/root/code/garage/garage/experiment/snapshotter.py", line 86, in save_itr_params
    with open(file_name, 'wb') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpc4b1c6zj/params.pkl'

======================================================================
ERROR: test_trpo_recurrent_cartpole (tests.garage.tf.algos.test_trpo_with_model.TestTRPO)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/code/garage/tests/garage/tf/algos/test_trpo_with_model.py", line 38, in test_trpo_recurrent_cartpole
    last_avg_ret = runner.train(n_epochs=10, batch_size=2048)
  File "/root/code/garage/garage/experiment/local_tf_runner.py", line 321, in train
    start_epoch=0)
  File "/root/code/garage/garage/experiment/local_tf_runner.py", line 407, in _train
    self.save(epoch, paths if store_paths else None)
  File "/root/code/garage/garage/experiment/local_tf_runner.py", line 210, in save
    snapshotter.save_itr_params(epoch, params)
  File "/root/code/garage/garage/experiment/snapshotter.py", line 86, in save_itr_params
    with open(file_name, 'wb') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpc4b1c6zj/params.pkl'

======================================================================
ERROR: test_ppo_pendulum_with_model (tests.garage.tf.algos.test_ppo_with_model.TestPPOWithModel)
Test PPO with model, with Pendulum environment.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/code/garage/tests/garage/tf/algos/test_ppo_with_model.py", line 42, in test_ppo_pendulum_with_model
    last_avg_ret = runner.train(n_epochs=10, batch_size=2048)
  File "/root/code/garage/garage/experiment/local_tf_runner.py", line 321, in train
    start_epoch=0)
  File "/root/code/garage/garage/experiment/local_tf_runner.py", line 407, in _train
    self.save(epoch, paths if store_paths else None)
  File "/root/code/garage/garage/experiment/local_tf_runner.py", line 210, in save
    snapshotter.save_itr_params(epoch, params)
  File "/root/code/garage/garage/experiment/snapshotter.py", line 86, in save_itr_params
    with open(file_name, 'wb') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpc4b1c6zj/params.pkl'

======================================================================
ERROR: test_npo_pendulum (tests.garage.tf.algos.test_npo.TestNPO)
Test NPO with Pendulum environment.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/code/garage/tests/garage/tf/algos/test_npo.py", line 41, in test_npo_pendulum
    last_avg_ret = runner.train(n_epochs=10, batch_size=2048)
  File "/root/code/garage/garage/experiment/local_tf_runner.py", line 321, in train
    start_epoch=0)
  File "/root/code/garage/garage/experiment/local_tf_runner.py", line 407, in _train
    self.save(epoch, paths if store_paths else None)
  File "/root/code/garage/garage/experiment/local_tf_runner.py", line 210, in save
    snapshotter.save_itr_params(epoch, params)
  File "/root/code/garage/garage/experiment/snapshotter.py", line 86, in save_itr_params
    with open(file_name, 'wb') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpc4b1c6zj/params.pkl'

----------------------------------------------------------------------
</details>

**Comment by ryanjulian** [comment]
@naeioi do you have any ideas why? this seems related to snapshots.

**Comment by zequnyu** [comment]
I'll try to debug it.

**Comment by zequnyu** [comment]
In local_tf_runner line 410:
`self.save(epoch, paths if store_paths else None)`
If store_paths is False, why do we bother calling the `save()` function?
@naeioi

**Comment by zequnyu** [comment]
@naeioi Should (or can) we reset the snapshotter when initialise the LocalRunner? I think it may be related to it.

**Comment by naeioi** [comment]
Sorry missed your ats. I think @gitanshu can confirm that https://github.com/rlworkgroup/garage/commit/3cf14b76e91acda52a2a1aeb54558f750a12665f can pass `make test`. Let me see what's going on here...

**Comment by naeioi** [comment]
The only case when python fails to open a file for writing saying file does not exist is that some prefix folder of target path does not exist. 

The bug is mostly introduced by https://github.com/rlworkgroup/garage/commit/af9eb8925e7226f4649a2280172b0be1cc3cfb0b#diff-376aa7ef418e8ba410f6c145d3364fdaR10 and https://github.com/rlworkgroup/garage/commit/af9eb8925e7226f4649a2280172b0be1cc3cfb0b#diff-240273a5a2365c0a8e548b8aa4fcf011R127, where two snapshottors are created.

**Comment by ryanjulian** [comment]
is this fixed?

**Comment by zequnyu** [comment]
Still working on it.

**Comment by zequnyu** [comment]
The problem is because temp dir is deleted [here](https://github.com/rlworkgroup/garage/blob/a5277f42912e654bc5f0cb541d4557ca3a2c0bb4/tests/garage/experiment/test_resume.py#L61) while the snapshotter (`_snapshot_dir`) isn't reset. This causes problem for all the following tests using ` save_itr_params()` for `_snapshot_dir` [here](https://github.com/rlworkgroup/garage/blob/a5277f42912e654bc5f0cb541d4557ca3a2c0bb4/garage/experiment/snapshotter.py#L59) should be None.

@gitanshu Please check if [this](https://github.com/rlworkgroup/garage/commit/d32ee6865fd6302f370af544ae0a58f98d970a4d) works on your machine.

**Comment by zequnyu** [comment]
I think we should add something to let the `snapshotter` reset itself in due time. Otherwise we are at risk when the life cycle of `snapshotter` becomes longer than the `LocalRunner`. What's the plan for the future usage of `snapshotter`? Use one `snapshotter` to handle several Runner? @naeioi

**Comment by naeioi** [comment]
Interesting. https://github.com/rlworkgroup/garage/blob/a5277f42912e654bc5f0cb541d4557ca3a2c0bb4/tests/garage/experiment/test_resume.py#L61 deletes a folder, but it is generated by tempfile, not directly from shopshotter. Why it breaks thing?

**Comment by gitanshu** [comment]
> The problem is because temp dir is deleted [here](https://github.com/rlworkgroup/garage/blob/a5277f42912e654bc5f0cb541d4557ca3a2c0bb4/tests/garage/experiment/test_resume.py#L61) while the snapshotter (`_snapshot_dir`) isn't reset. This causes problem for all the following tests using ` save_itr_params()` for `_snapshot_dir` [here](https://github.com/rlworkgroup/garage/blob/a5277f42912e654bc5f0cb541d4557ca3a2c0bb4/garage/experiment/snapshotter.py#L59) should be None.
> 
> @gitanshu Please check if [this](https://github.com/rlworkgroup/garage/commit/d32ee6865fd6302f370af544ae0a58f98d970a4d) fix works on your machine.

@zequnyu no idea what's going on, but the patch works

**Comment by zequnyu** [comment]
We are currently instantiate the `shopshotter` inside its implementation [class](https://github.com/rlworkgroup/garage/blob/a5277f42912e654bc5f0cb541d4557ca3a2c0bb4/garage/experiment/snapshotter.py#L127). When doing tests, `from garage.experiment import snapshotter` in LocalRunner will only import once. This means we are using the same `snapshotter` in tests. That's why I ask whether we plan to use one snapshotter to handle several Runner. I think it is because `_snapshot_dir` is not set to `None` so following tests mistake the path.

**Comment by naeioi** [comment]
Ah got your idea. Nice catch! Please make this a PR. @zequnyu

**Comment by ryanjulian** [comment]
@zequnyu Good catch!

To solve this issue long-term, we should probably have the LocalRunner create a snapshotter instance it owns, rather than having the process-global snapshotter. It is process-global because of previous design decisions, but it doesn't have to be.

**Comment by naeioi** [comment]
I agree. This global process snapshotter is flaky. @gautams3 also experienced a similar bug, that there were two instances of snapshotter, of which one is initialized and the other is not.

Because we take snapshot only at LocalRunner, I think it will not be too much effort removing this global snapshotter.

**Comment by zequnyu** [comment]
@ryanjulian Shall I file an issue and address the change?

**Comment by ryanjulian** [comment]
yes please!
