### ISSUE TITLE
NoisyObservationEnv and DelayedActionEnv are broken

### ISSUE THREAD

**Issue by ryanjulian** [rlworkgroup/garage#70]
```sh
Traceback (most recent call last):
  File "tests/envs/test_envs.py", line 69, in <module>
    envs.append(DelayedActionEnv(CartpoleEnv()))
  File "/home/rjulian/code/garage/rllab/envs/noisy_env.py", line 63, in __init__
    super(DelayedActionEnv, self).__init__(env)
  File "/home/rjulian/code/garage/rllab/envs/proxy_env.py", line 8, in __init__
    Serializable.quick_init(self, locals())
  File "/home/rjulian/code/garage/rllab/core/serializable.py", line 30, in quick_init
    in_order_args = [locals_[arg] for arg in spec.args][1:]
  File "/home/rjulian/code/garage/rllab/core/serializable.py", line 30, in <listcomp>
    in_order_args = [locals_[arg] for arg in spec.args][1:]
KeyError: 'env'
```

**Comment by ryanjulian** [comment]
Fixed in #58
