### ISSUE TITLE
Nightly builds are failing

### ISSUE THREAD

**Issue by ryanjulian** [rlworkgroup/garage#768]
https://travis-ci.com/rlworkgroup/garage/jobs/213465246

I think it may have been a API change in pyglet. we may need to pin that dep.

**Comment by ilinojkovic** [comment]
Is this maybe connected:
```
Traceback (most recent call last):
  File "run_scripts/2019_07_06_22_59_33_0000/run.py", line 15, in <module>
    from garage.envs import normalize
  File "/venvs/rl_env/lib/python3.6/site-packages/garage/envs/__init__.py", line 1, in <module>
    from garage.envs.base import GarageEnv
  File "/venvs/rl_env/lib/python3.6/site-packages/garage/envs/base.py", line 7, in <module>
    from gym.envs.classic_control.rendering import SimpleImageViewer
  File "/venvs/rl_env/lib/python3.6/site-packages/gym/envs/classic_control/rendering.py", line 27, in <module>
    from pyglet.gl import *
  File "/venvs/rl_env/lib/python3.6/site-packages/pyglet/gl/__init__.py", line 237, in <module>
    import pyglet.window
  File "/venvs/rl_env/lib/python3.6/site-packages/pyglet/window/__init__.py", line 1868, in <module>
    gl._create_shadow_window()
  File "/venvs/rl_env/lib/python3.6/site-packages/pyglet/gl/__init__.py", line 209, in _create_shadow_window
    _shadow_window = Window(width=1, height=1, visible=False)
  File "/venvs/rl_env/lib/python3.6/site-packages/pyglet/window/xlib/__init__.py", line 171, in __init__
    super(XlibWindow, self).__init__(*args, **kwargs)
  File "/venvs/rl_env/lib/python3.6/site-packages/pyglet/window/__init__.py", line 574, in __init__
    display = pyglet.canvas.get_display()
  File "/venvs/rl_env/lib/python3.6/site-packages/pyglet/canvas/__init__.py", line 96, in get_display
    return Display()
  File "/venvs/rl_env/lib/python3.6/site-packages/pyglet/canvas/xlib.py", line 120, in __init__
    raise NoSuchDisplayException('Cannot connect to "%s"' % name)
pyglet.canvas.xlib.NoSuchDisplayException: Cannot connect to "None"
```
I'm trying to run scripts on cluster without display.
