### ISSUE TITLE
Garage does not run without display (pyglet)

### ISSUE THREAD

**Issue by timediv** [rlworkgroup/garage#847]
Not all use cases require environment rendering. Can we get rid of this default import?

```
Traceback (most recent call last):
    from garage.tf.envs import TfEnv
  File "/home//garage/env/lib/python3.6/site-packages/garage/tf/envs/__init__.py", line 1, in <module>
    from garage.tf.envs.base import TfEnv
  File "/home//garage/env/lib/python3.6/site-packages/garage/tf/envs/base.py", line 4, in <module>
    from garage.envs import GarageEnv
  File "/home//garage/env/lib/python3.6/site-packages/garage/envs/__init__.py", line 1, in <module>
    from garage.envs.base import GarageEnv
  File "/home//garage/env/lib/python3.6/site-packages/garage/envs/base.py", line 7, in <module>
    from gym.envs.classic_control.rendering import SimpleImageViewer
  File "/home//garage/env/lib/python3.6/site-packages/gym/envs/classic_control/rendering.py", line 27, in <module>
    from pyglet.gl import *
  File "/home//garage/env/lib/python3.6/site-packages/pyglet/gl/__init__.py", line 239, in <module>
    import pyglet.window
  File "/home//garage/env/lib/python3.6/site-packages/pyglet/window/__init__.py", line 1896, in <module>
    gl._create_shadow_window()
  File "/home//garage/env/lib/python3.6/site-packages/pyglet/gl/__init__.py", line 208, in _create_shadow_window
    _shadow_window = Window(width=1, height=1, visible=False)
  File "/home//garage/env/lib/python3.6/site-packages/pyglet/window/xlib/__init__.py", line 166, in __init__
    super(XlibWindow, self).__init__(*args, **kwargs)
  File "/home//garage/env/lib/python3.6/site-packages/pyglet/window/__init__.py", line 501, in __init__
    display = get_platform().get_default_display()
  File "/home//garage/env/lib/python3.6/site-packages/pyglet/window/__init__.py", line 1845, in get_default_display
    return pyglet.canvas.get_display()
  File "/home//garage/env/lib/python3.6/site-packages/pyglet/canvas/__init__.py", line 82, in get_display
    return Display()
  File "/home//garage/env/lib/python3.6/site-packages/pyglet/canvas/xlib.py", line 86, in __init__
    raise NoSuchDisplayException('Cannot connect to "%s"' % name)
pyglet.canvas.xlib.NoSuchDisplayException: Cannot connect to "None"
```

**Comment by ryanjulian** [comment]
Good catch. FWIW you can always avoid this using our pre-built Docker container with a fake display
```sh
make run-headless RUN_CMD="python run/my/cool/launcher.py"
```

@gitanshu can you make this import conditional on actually needing to access these classes?
