### ISSUE TITLE
run_experiment_lite is broken

### ISSUE THREAD

**Issue by ryanjulian** [rlworkgroup/garage#92]
```sh
(garage) rjulian@nyquist:~/code/garage$ python examples/trpo_gym_pendulum.py 
2018-06-15 11:01:19.226010: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
Traceback (most recent call last):
  File "examples/trpo_gym_pendulum.py", line 46, in <module>
    seed=1,
  File "/home/rjulian/code/garage/garage/misc/instrument.py", line 482, in run_experiment_lite
    task["exp_name"])
  File "/home/rjulian/miniconda2/envs/garage/lib/python3.5/posixpath.py", line 89, in join
    genericpath._check_arg_types('join', a, *p)
  File "/home/rjulian/miniconda2/envs/garage/lib/python3.5/genericpath.py", line 143, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'NoneType
```

**Comment by zhanpenghe** [comment]
I did not dig much but by setting garage.config.AWS_S3_PATH = "" could temporarily fix this issue.

**Comment by ryanjulian** [comment]
False alarm--local bug because smh my `config_personal.py` was an empty file.
