### ISSUE TITLE
Some envs are broken in render()

### ISSUE THREAD

**Issue by ryanjulian** [rlworkgroup/garage#93]
```sh
(garage) rjulian@nyquist:~/code/garage$ nose2 tests.envs
2018-06-15 11:26:49.815393: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
.Testing <class 'garage.envs.grid_world_env.GridWorldEnv'>
ETesting <class 'garage.envs.box2d.cartpole_env.CartpoleEnv'>
.Testing <class 'garage.envs.box2d.car_parking_env.CarParkingEnv'>
.Testing <class 'garage.envs.box2d.cartpole_swingup_env.CartpoleSwingupEnv'>
.Testing <class 'garage.envs.box2d.double_pendulum_env.DoublePendulumEnv'>
.Testing <class 'garage.envs.box2d.mountain_car_env.MountainCarEnv'>
.Testing <class 'garage.envs.mujoco.point_env.PointEnv'>
Creating window glfw
.Testing <class 'garage.envs.mujoco.walker2d_env.Walker2DEnv'>
Creating window glfw
.Testing <class 'garage.envs.mujoco.swimmer_env.SwimmerEnv'>
Creating window glfw
.Testing <class 'garage.envs.mujoco.simple_humanoid_env.SimpleHumanoidEnv'>
Creating window glfw
.Testing <class 'garage.envs.mujoco.inverted_double_pendulum_env.InvertedDoublePendulumEnv'>
Creating window glfw
.Testing <class 'garage.envs.mujoco.hopper_env.HopperEnv'>
Creating window glfw
.Testing <class 'garage.envs.mujoco.half_cheetah_env.HalfCheetahEnv'>
Creating window glfw
.Testing <class 'garage.envs.mujoco.gather.point_gather_env.PointGatherEnv'>
ETesting <class 'garage.envs.mujoco.gather.swimmer_gather_env.SwimmerGatherEnv'>
ETesting <class 'garage.envs.mujoco.gather.ant_gather_env.AntGatherEnv'>
ETesting <class 'garage.envs.mujoco.maze.point_maze_env.PointMazeEnv'>
Creating window glfw
.Testing <class 'garage.envs.mujoco.maze.swimmer_maze_env.SwimmerMazeEnv'>
Creating window glfw
.Testing <class 'garage.envs.mujoco.maze.ant_maze_env.AntMazeEnv'>
Creating window glfw
.Testing <class 'garage.envs.proxy_env.ProxyEnv'>
ETesting <class 'garage.envs.identification_env.IdentificationEnv'>
.Testing <class 'garage.envs.noisy_env.NoisyObservationEnv'>
.Testing <class 'garage.envs.noisy_env.DelayedActionEnv'>
.Testing <class 'garage.envs.normalized_gym_env.NormalizedGymEnv'>
ETesting <class 'gym.wrappers.time_limit.TimeLimit'>
.
======================================================================
ERROR: tests.envs.test_envs.test_env:1
<garage.envs.grid_world_env.GridWorldEnv object at 0x7f3c2becf9e8>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rjulian/code/garage/tests/envs/test_envs.py", line 89, in test_env
    env.render()
  File "/home/rjulian/miniconda2/envs/garage/lib/python3.5/site-packages/gym/core.py", line 111, in render
    raise NotImplementedError
NotImplementedError

======================================================================
ERROR: tests.envs.test_envs.test_env:14
<garage.envs.mujoco.gather.point_gather_env.PointGatherEnv object at 0x7f3b2825
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rjulian/code/garage/tests/envs/test_envs.py", line 89, in test_env
    env.render()
  File "/home/rjulian/code/garage/garage/envs/mujoco/gather/gather_env.py", line 405, in render
    self.get_viewer()
  File "/home/rjulian/code/garage/garage/envs/mujoco/gather/gather_env.py", line 389, in get_viewer
    self.wrapped_env.viewer = GatherViewer(self)
  File "/home/rjulian/code/garage/garage/envs/mujoco/gather/gather_env.py", line 35, in __init__
    super(GatherViewer, self).__init__()
TypeError: __init__() missing 1 required positional argument: 'sim'

======================================================================
ERROR: tests.envs.test_envs.test_env:15
<garage.envs.mujoco.gather.swimmer_gather_env.SwimmerGatherEnv object at 0x7f3b
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rjulian/code/garage/tests/envs/test_envs.py", line 89, in test_env
    env.render()
  File "/home/rjulian/code/garage/garage/envs/mujoco/gather/gather_env.py", line 405, in render
    self.get_viewer()
  File "/home/rjulian/code/garage/garage/envs/mujoco/gather/gather_env.py", line 389, in get_viewer
    self.wrapped_env.viewer = GatherViewer(self)
  File "/home/rjulian/code/garage/garage/envs/mujoco/gather/gather_env.py", line 35, in __init__
    super(GatherViewer, self).__init__()
TypeError: __init__() missing 1 required positional argument: 'sim'

======================================================================
ERROR: tests.envs.test_envs.test_env:16
<garage.envs.mujoco.gather.ant_gather_env.AntGatherEnv object at 0x7f3b282571d0
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rjulian/code/garage/tests/envs/test_envs.py", line 89, in test_env
    env.render()
  File "/home/rjulian/code/garage/garage/envs/mujoco/gather/gather_env.py", line 405, in render
    self.get_viewer()
  File "/home/rjulian/code/garage/garage/envs/mujoco/gather/gather_env.py", line 389, in get_viewer
    self.wrapped_env.viewer = GatherViewer(self)
  File "/home/rjulian/code/garage/garage/envs/mujoco/gather/gather_env.py", line 35, in __init__
    super(GatherViewer, self).__init__()
TypeError: __init__() missing 1 required positional argument: 'sim'

======================================================================
ERROR: tests.envs.test_envs.test_env:20
<garage.envs.proxy_env.ProxyEnv object at 0x7f3c2becf940>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rjulian/code/garage/tests/envs/test_envs.py", line 89, in test_env
    env.render()
  File "/home/rjulian/code/garage/garage/envs/proxy_env.py", line 30, in render
    return self._wrapped_env.render(*args, **kwargs)
  File "/home/rjulian/miniconda2/envs/garage/lib/python3.5/site-packages/gym/core.py", line 111, in render
    raise NotImplementedError
NotImplementedError

======================================================================
ERROR: tests.envs.test_envs.test_env:24
Normalized: <CartpoleEnv instance>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rjulian/code/garage/tests/envs/test_envs.py", line 89, in test_env
    env.render()
  File "/home/rjulian/miniconda2/envs/garage/lib/python3.5/site-packages/gym/core.py", line 284, in render
    return self.env.render(mode)
  File "/home/rjulian/code/garage/garage/envs/box2d/box2d_env.py", line 358, in render
    raise NotImplementedError
NotImplementedError

----------------------------------------------------------------------
Ran 26 tests in 5.385s
```
I think this is due to the `gym.Env` interface

**Comment by jonashen** [comment]
The NotImplementedError envs depend on NormalizedEnv.

**Comment by ryanjulian** [comment]
This is with NormalizedEnv. I think it's because they are calling through to a render() function (which is part of the `gym.Env` interface), but the child classes don't override `render()`--so it calls through to `gym.Env.render()`, which raises `NotImplementedError` (because the author was supposed to override the base class)

**Comment by jonashen** [comment]
Also, I was looking into the `TypeError: __init__() missing 1 required positional argument: 'sim'` error, and it's because MjViewer needs to be passed sim into its __init__ function, but this change requires extensive understanding of where MjViewer is being used.

**Comment by ryanjulian** [comment]
Yes, that one is not covered by `render()`.
